In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
# DATA CELL
# DO NOT EDIT THIS CELL
import numpy as np
import matplotlib.pyplot as plt

# Generate synthetic data
np.random.seed(42)

# Number of samples and features
num_samples = 200
num_features = 5

# Generate random features
X = np.random.randn(num_samples, num_features)

# Generate true coefficients for each feature
true_coef = np.random.uniform(-2, 2, size=num_features)

# Generate noise
noise = np.random.normal(loc=0, scale=0.5, size=num_samples)

# Generate target variable
y = np.dot(X, true_coef) + noise

# Split data into training and test sets
split = int(0.8 * num_samples)  # 80% training, 20% test
X_train, X_test = X[:split].T, X[split:].T
y_train, y_test = y[:split], y[split:]

In [34]:
X_train

array([[ 0.49671415, -0.23413696, -0.46341769, -0.56228753,  1.46564877,
         0.11092259, -0.60170661, -1.22084365,  0.73846658, -0.71984421,
         0.32408397,  0.93128012, -0.47917424,  1.35624003,  0.36139561,
         0.8219025 , -0.21967189, -0.50175704,  0.09707755, -1.46351495,
        -1.41537074,  0.40405086, -1.91877122,  0.30154734,  0.79103195,
         2.19045563, -1.55066343,  1.54993441,  0.22745993,  0.78182287,
         0.25049285, -0.71435142, -0.97468167,  0.41278093, -0.88951443,
         0.82718325,  0.62566735,  0.71400049, -0.44651495,  0.38531738,
         0.35778736, -0.93782504,  0.57089051,  0.75896922,  2.31465857,
         1.0889506 , -0.73036663,  0.63391902, -0.79252074, -0.33450124,
        -1.26088395, -0.48423407, -0.92693047, -1.24778318,  1.44127329,
         0.46210347,  0.11351735, -1.9520878 , -0.20812225, -0.6929096 ,
        -0.82899501,  0.11732738, -0.2176812 ,  0.02100384,  0.09699596,
        -1.21418861, -0.01224677, -0.14705738, -0.8

In [35]:
X_train.shape

(5, 160)

In [36]:
dummy_feature= np.ones(X_train.shape[1])

In [37]:
X_train=np.concatenate((dummy_feature.reshape(1,-1), X_train), axis=0)

In [38]:
X_train.shape

(6, 160)

In [39]:
X_train

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1. 

In [40]:
X_test.shape

(5, 40)

In [41]:
dummy_test_feature= np.ones(X_test.shape[1])

In [42]:
X_test=np.concatenate((dummy_test_feature.reshape(1,-1), X_test) , axis=0)

In [43]:
X_test

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.93828381, -0.30917212, -0.18687164, -1.48556037, -0.51728845,
         1.45338448, -1.34445051,  0.23421473, -0.04946371,  0.49245126,
        -0.62314053, -0.57074629,  0.20292302, -0.38770156, -0.17694723,
         1.79455786,  2.52693243,  1.84670733,  0.82048218,  0.64870989,
         0.36867331,  0.04643655, -0.30777823,  0.27902153,  1.07363175,
        -1.5231869 , -0.55519953, -0.50205422, -1.

In [44]:
np.linalg.pinv( X_train.T)  @ y_train

array([ 0.03635182, -1.26278497, -1.56596725,  0.61933777,  0.83287999,
       -1.87103269])

In [45]:
w_star=np.linalg.pinv(X_train @ X_train.T) @ X_train @ y_train

In [46]:
round(np.linalg.norm(w_star),2)

2.94

In [47]:
y_pred= X_train.T @ w_star

In [48]:
error=(y_train-y_pred)**2

In [49]:
round(0.5* error.mean(),2)

0.13

In [50]:
y_pred_test=X_test.T @ w_star

In [51]:
error_test=(y_test-y_pred_test)**2

In [52]:
round(0.5 * error_test.mean(),2)

0.11